Fail test if output incorrect

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,3 +23,8 @@ jobs:
 
       - run: |
           echo '${{ steps.upload-multiple-artifacts.outputs.artifact-ids }}'
+          EXPECTED='{"./baa.jpg":5751097443,"./foo.png":5751097556,"./sheep.txt":5751097695}'
+          if [ '${{ steps.upload-multiple-artifacts.outputs.artifact-ids }}' != "$EXPECTED" ]; then
+            echo "Assertion error"
+            exit 1;
+          fi
